services:
  axon:
    image: axon:latest
    ports:
      - "8000:8000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OTEL_SERVICE_NAME=axon
      - OTEL_RESOURCE_ATTRIBUTES=service.name=axon,service.version=0.1.0
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      #- OTEL_LOG_LEVEL=debug
    depends_on:
      - otel-collector
      - jaeger
      - prometheus
    networks:
      - axon-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # UDP port for the Jaeger agent
      - "16686:16686"   # Web UI
      - "14268:14268"   # HTTP port for spans
    networks:
      - axon-network

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=otlp-write-receiver
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - axon-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    depends_on:
      - jaeger
      - prometheus
    networks:
      - axon-network

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./observability/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000"
    networks:
      - axon-network

networks:
  axon-network:
    driver: bridge
